name: FoodGen application continuous deployment
on:
  pull_request:
    branches: [ prod ]
    paths:
      - 'src/**'
      - '.github/workflows/cd.yml'
  push:
    branches: [ prod ]
    paths:
      - 'src/**'
      - '.github/workflows/cd.yml'

jobs:
  project-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - run: chmod +x mvn
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package

  docker-build:
    if: ${{ github.ref == 'refs/heads/prod' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Dashboard to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: foodgen/back:latest
